name: 'randy_pitcher_workspace'
version: '1.0.0'

# change this to match the profile name you used when setting up your dbt authentication.
# Don't remember? Open `~/.dbt/profiles.yml` to see. If it's not there, you haven't set one up yet.
# Make an LLM tell you how to do it. I believe in you 💽
profile: 'iceberg_overlay_workspace'

vars:
  deployment_environment: "{{target.name}}"

models:
  randy_pitcher_workspace:
    +materialized: view
    +auto_liquid_cluster: true
    +persist_docs:
      relation: true
      columns: true

    staging:
      +tags: staging
      +schema: staging

    modeled:
      +materialized: table
      +tags: modeled
      +schema: modeled

    mart:
      +materialized: table
      +tags: mart
      +schema: mart
