[project]
name = "kafka_cdc_simulation"
version = "0.1.0"
description = "Kafka CDC processing simulation"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.1",
    "confluent-kafka>=2.4.0",
    "boto3>=1.39.9",
]