version: '3.8'

services:
  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/app/application.yml
    env_file:
      - ../../.env 