{#-
  Feature table for the segment classifier: valid members only, one-hot device
  columns generated by the one_hot() dynamic-SQL macro.

  The device list is a COMPILE-TIME project var (pattern_device_types), not a
  query: a model's input signature must not change because new data arrived.
  Compare audience_region_mix.sql, which derives its columns at RUN time.

  This is the hand-off point of the lifecycle: dbt builds features, MLflow
  trains on them (scripts/train_segment_classifier.py), and the scoring models
  read the registered model back by name.
-#}
select
    member_id,
    region_code_clean as region_code,
    timezone_clean as timezone,
    sessions_30d,
    avg_watch_minutes,
    days_since_signup,
    {{ one_hot('device_type', var('pattern_device_types'), prefix='device') }},
    in_segment
from {{ ref('audience_members_validated') }}
where is_valid
